services:
  signos-vitales-consumidor:
    image: ms-signos-vitales-consumidor
    container_name: signos-vitales-consumidor
    ports:
      - "8082:8082"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: "172.31.82.234:9092"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m" 
        max-file: "3"
    networks:
      - kafka_kafka-net

networks:
  kafka_kafka-net:
    external: true
